// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-shifts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}
function failure(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function ok(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { result: data }
  };
}

// src/lib/mcp/tools/list-shifts.ts
var list_shifts_default = defineTool({
  name: "list_shifts",
  title: "List shifts",
  description: "List the signed-in user's caregiver shifts, optionally filtered by date range, caregiver name, or payment status. Returns date, times, hours, caregiver, location, costs and payment status.",
  inputSchema: {
    from_date: z.string().optional().describe("Only include shifts on or after this ISO date (YYYY-MM-DD)."),
    to_date: z.string().optional().describe("Only include shifts on or before this ISO date (YYYY-MM-DD)."),
    caregiver_name: z.string().optional().describe("Filter to shifts whose caregiver name contains this text."),
    payment_status: z.enum(["paid", "unpaid"]).optional().describe("Filter by payment status."),
    limit: z.number().optional().describe("Maximum number of shifts to return (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const limit = Math.min(Math.max(input.limit ?? 50, 1), 200);
    let query = supabaseForUser(ctx).from("shifts").select("*").order("date", { ascending: false }).limit(limit);
    if (input.from_date) query = query.gte("date", input.from_date);
    if (input.to_date) query = query.lte("date", input.to_date);
    if (input.caregiver_name)
      query = query.ilike("caregiver_name", `%${input.caregiver_name}%`);
    if (input.payment_status)
      query = query.eq("payment_status", input.payment_status);
    const { data, error } = await query;
    if (error) return failure(error.message);
    return ok({ count: data?.length ?? 0, shifts: data ?? [] });
  }
});

// src/lib/mcp/tools/list-caregivers.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_caregivers_default = defineTool2({
  name: "list_caregivers",
  title: "List caregivers",
  description: "List the signed-in user's caregivers with their type (private_paid, family_member, volunteer) and hourly rate.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("caregivers").select("id, name, caregiver_type, hourly_rate, updated_at").order("name", { ascending: true });
    if (error) return failure(error.message);
    return ok({ count: data?.length ?? 0, caregivers: data ?? [] });
  }
});

// src/lib/mcp/tools/shift-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var shift_summary_default = defineTool3({
  name: "shift_summary",
  title: "Summarize shifts",
  description: "Summarize the signed-in user's shifts over a date range: total hours, total payment, total expenses (travel + parking), and per-caregiver breakdown.",
  inputSchema: {
    from_date: z2.string().describe("Start of the range, ISO date (YYYY-MM-DD)."),
    to_date: z2.string().describe("End of the range, ISO date (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("shifts").select(
      "date, caregiver_name, caregiver_type, total_hours, payment_amount, travel_cost, parking_cost, payment_status"
    ).gte("date", from_date).lte("date", to_date);
    if (error) return failure(error.message);
    const rows = data ?? [];
    const byCaregiver = {};
    let hours = 0;
    let payment = 0;
    let expenses = 0;
    let unpaid = 0;
    for (const row of rows) {
      const rowExpenses = (row.travel_cost ?? 0) + (row.parking_cost ?? 0);
      hours += row.total_hours ?? 0;
      payment += row.payment_amount ?? 0;
      expenses += rowExpenses;
      if (row.payment_status === "unpaid") unpaid += 1;
      const entry = byCaregiver[row.caregiver_name] ??= {
        shifts: 0,
        hours: 0,
        payment: 0,
        expenses: 0
      };
      entry.shifts += 1;
      entry.hours += row.total_hours ?? 0;
      entry.payment += row.payment_amount ?? 0;
      entry.expenses += rowExpenses;
    }
    return ok({
      from_date,
      to_date,
      total_shifts: rows.length,
      unpaid_shifts: unpaid,
      total_hours: Number(hours.toFixed(2)),
      total_payment: Number(payment.toFixed(2)),
      total_expenses: Number(expenses.toFixed(2)),
      grand_total: Number((payment + expenses).toFixed(2)),
      by_caregiver: byCaregiver
    });
  }
});

// src/lib/mcp/tools/set-payment-status.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var set_payment_status_default = defineTool4({
  name: "set_payment_status",
  title: "Set shift payment status",
  description: "Mark one of the signed-in user's shifts as paid or unpaid, optionally setting the payment date.",
  inputSchema: {
    shift_id: z3.string().describe("The shift id, as returned by list_shifts."),
    payment_status: z3.enum(["paid", "unpaid"]).describe("New payment status."),
    payment_date: z3.string().optional().describe("ISO date (YYYY-MM-DD) the payment was made. Only used when marking as paid.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
  handler: async ({ shift_id, payment_status, payment_date }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const update = { payment_status };
    if (payment_status === "paid") {
      if (payment_date) update.payment_date = payment_date;
    } else {
      update.payment_date = null;
    }
    const { data, error } = await supabaseForUser(ctx).from("shifts").update(update).eq("id", shift_id).select();
    if (error) return failure(error.message);
    if (!data?.length) return failure("No shift found with that id.");
    return ok({ shift: data[0] });
  }
});

// src/lib/mcp/tools/create-shift.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
function hoursBetween(start, end) {
  const [sh, sm] = start.split(":").map(Number);
  const [eh, em] = end.split(":").map(Number);
  let minutes = eh * 60 + em - (sh * 60 + sm);
  if (minutes <= 0) minutes += 24 * 60;
  return Number((minutes / 60).toFixed(2));
}
var create_shift_default = defineTool5({
  name: "create_shift",
  title: "Create shift",
  description: "Create a new caregiver shift for the signed-in user. Payment amount is computed from the caregiver's hourly rate unless explicitly provided.",
  inputSchema: {
    date: z4.string().describe("Shift date, ISO (YYYY-MM-DD)."),
    start_time: z4.string().describe("Start time, HH:mm."),
    end_time: z4.string().describe("End time, HH:mm. May be earlier than start for overnight shifts."),
    caregiver_name: z4.string().describe("Caregiver name."),
    caregiver_type: z4.enum(["private_paid", "family_member", "volunteer"]).describe("Caregiver type. Only private_paid shifts are billable."),
    location_type: z4.enum(["hospital", "home", "institution"]).describe("Location type."),
    location_name: z4.string().describe("Location name, e.g. hospital or ward name."),
    payment_amount: z4.number().optional().describe("Override the computed labor payment amount."),
    payment_method: z4.enum(["bank_transfer", "paybox", "bit", "cash"]).optional().describe("Payment method (default bank_transfer)."),
    payment_status: z4.enum(["paid", "unpaid"]).optional().describe("Payment status (default unpaid)."),
    travel_cost: z4.number().optional().describe("Expenses amount (default 0)."),
    notes: z4.string().optional().describe("Free-text notes about the shift.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const totalHours = hoursBetween(input.start_time, input.end_time);
    const billable = input.caregiver_type === "private_paid";
    let paymentAmount = input.payment_amount ?? 0;
    if (input.payment_amount === void 0 && billable) {
      const { data: caregiver } = await supabase.from("caregivers").select("hourly_rate").eq("name", input.caregiver_name).maybeSingle();
      paymentAmount = Number(((caregiver?.hourly_rate ?? 0) * totalHours).toFixed(2));
    }
    if (!billable) paymentAmount = 0;
    const { data, error } = await supabase.from("shifts").insert({
      id: crypto.randomUUID(),
      user_id: userId,
      date: input.date,
      start_time: input.start_time,
      end_time: input.end_time,
      total_hours: totalHours,
      caregiver_name: input.caregiver_name,
      caregiver_type: input.caregiver_type,
      location_type: input.location_type,
      location_name: input.location_name,
      payment_amount: paymentAmount,
      payment_method: input.payment_method ?? "bank_transfer",
      payment_status: billable ? input.payment_status ?? "unpaid" : "unpaid",
      travel_cost: billable ? input.travel_cost ?? 0 : 0,
      parking_cost: 0,
      notes: input.notes ?? null
    }).select();
    if (error) return failure(error.message);
    return ok({ shift: data?.[0] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "jllablsoqogfplecqkyn";
var mcp_default = defineMcp({
  name: "aidflow-mcp",
  title: "AidFlow",
  version: "0.1.0",
  instructions: "Tools for AidFlow, a caregiver shift tracker. Use list_shifts and list_caregivers to read the signed-in user's data, shift_summary for totals over a date range, create_shift to log a new shift, and set_payment_status to mark a shift paid or unpaid. All data is scoped to the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_shifts_default, list_caregivers_default, shift_summary_default, create_shift_default, set_payment_status_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
